server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/carts/**
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/ 

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    reactor.netty: DEBUG 