server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/user_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: U2hEamZzMnh2YmZxa2xqajEyMzQ1Njc4
  expiration: 86400000 
logging:
  level:
       org.springframework.security: DEBUG 