server:
  port: 8082
  address: 0.0.0.0
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/supnon_db
    username: supnon
    password: supnon123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/ 